Lapin-Learn/main-website

src/components/molecules/practice-breadcrumb.tsx
src/components/molecules/simulated-tests/filtered-skill-card.tsx
src/components/organisms/base-table.tsx
src/components/organisms/result/answer-guidance-content.tsx
src/components/organisms/result/part-answers-card.tsx
src/components/organisms/select-mode-dialog/index.tsx
src/components/organisms/select-mode-dialog/use-select-mode-dialog.ts
src/components/organisms/simulated-test/simulated-test-card.tsx
src/components/pages/result/index.tsx
src/components/pages/simulated-test/reading.tsx
src/components/templates/test-header-layout.tsx
src/components/ui/typography.tsx
src/services/simulated-test.ts

This PR is aim for fixing a lot of bugs, including:
- Crash when create a session (start test)
- After submit a test, it navigate to result screen and crash
- A lot of warning in devtools
- Sumit null responses
- Start test RL
- Check console devtools
- submit null response -> return a toast
https://datn.atlassian.net/browse/LAP-646
https://datn.atlassian.net/browse/LAP-661

fix(LAP-661 LAP-646): crash in create and view result ST

---

src/components/organisms/result-analysis-table/column.tsx
src/components/organisms/result-analysis-table/table.tsx
src/components/organisms/result/answer-guidance-content.tsx
src/components/pages/result/index.tsx
src/hooks/react-query/use-simulated-test.ts
src/i18n/locales/en/collection.json
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/simulated-test.json
src/lib/enums.ts
src/lib/types/simulated-test.type.ts

Result analysis based on question type, each shows correct and skip answers, accuracy and question lists.
[screen-capture (13).webm](https://github.com/user-attachments/assets/b1628e7c-b618-4d20-8c51-d1f4a34513cf)

feat(LAP-677): result analysis shows unanswered

---

src/components/editor/local-custom-extensions/input-field/input-field.tsx
src/components/molecules/question-navigator-button.tsx
src/components/organisms/question-groups/matching-headings-question-group.tsx
src/components/organisms/question-groups/matching-information-question-group.tsx
src/components/organisms/question-groups/multiple-choice-question-group.tsx
src/components/organisms/result-analysis-table/column.tsx
src/components/organisms/result-analysis-table/table.tsx
src/components/organisms/result/answer-guidance-content.tsx
src/components/organisms/simulated-test-dialog/exit-dialog.tsx
src/components/organisms/simulated-test-dialog/submit-dialog.tsx
src/components/pages/result/index.tsx
src/components/pages/simulated-test/listening.tsx
src/components/pages/simulated-test/reading.tsx
src/components/ui/checkbox.tsx
src/hooks/react-query/use-simulated-test.ts
src/i18n/locales/en/collection.json
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/simulated-test.json
src/lib/enums.ts
src/lib/types/simulated-test.type.ts
src/lib/utils/index.ts
src/services/simulated-test.ts

This PR aims to creating analysis tab and enhance the UI of full-screen dialog result.

feat: content result reading and result analysis

---

src/components/molecules/overall-band-score-chart.tsx
src/components/molecules/simulated-tests/filtered-skill-card.tsx
src/components/organisms/select-mode-dialog/index.tsx
src/components/organisms/simulated-test-table/column.tsx
src/components/organisms/speaking-question/speaking-part-one-and-three.tsx
src/components/organisms/speaking-question/speaking-part-two.tsx
src/components/pages/profile/history.tsx
src/components/pages/profile/index.tsx
src/hooks/react-query/use-simulated-test.ts
src/hooks/use-audio-recording.tsx
src/lib/types/simulated-test.type.ts
src/lib/types/user.type.ts
src/lib/utils/index.ts
src/services/simulated-test.ts

feat(lap-680): fix some bugs

---

src/components/molecules/skill-filter.tsx
src/components/organisms/result/part-answers-card.tsx
src/components/organisms/skill-evaluation-line-chart.tsx
src/components/pages/profile/history.tsx
src/components/pages/result/reading-listening-result.tsx
src/hooks/react-query/use-simulated-test.ts
src/i18n/locales/en/profile.json
src/i18n/locales/vi/profile.json
src/lib/consts.ts
src/lib/types/simulated-test.type.ts
src/services/simulated-test.ts

Evaluation chart by skill in profile
https://datn.atlassian.net/browse/LAP-673

feat(LAP-673): evaluation chart by skill in profile

---

src/components/organisms/select-mode-dialog/index.tsx
src/hooks/react-query/useAuth.ts
src/i18n/i18n.tsx
src/i18n/locales/en/auth.json
src/i18n/locales/en/common.json
src/i18n/locales/en/error.json
src/i18n/locales/en/practice.json
src/i18n/locales/en/success.json
src/i18n/locales/vi/auth.json
src/i18n/locales/vi/common.json
src/i18n/locales/vi/error.json
src/i18n/locales/vi/practice.json
src/i18n/locales/vi/success.json
src/services/auth.ts

- Fix showing "null" accessToken when signing up and not routing to verify pages, 
- Fix alert messages of simulated test
- Update i18n for success and error messages of Authentication
Signing up with a new email to check whether the verify-otp page is showing and not showing toast.
Check toast messages of Authentication
Check alert message of simulated test

feat(lap-700): authentication, routing bugs and i18n with error messages

---

src/App.tsx
src/firebaseConfig.ts
src/hooks/react-query/use-simulated-test.ts
src/hooks/react-query/useAuth.ts
src/lib/consts.ts

Analytics for tracking screens view, login and startSimulatedTest
Login, vô vài page rồi qua firebase coi trong Analytics Dashboard

feat(lap-682): analytics

---

src/components/organisms/select-mode-dialog/index.tsx
src/lib/types/simulated-test.type.ts

fix: pass skill test id when start test

---

src/components/organisms/base-table.tsx
src/components/organisms/sidebar/side-bar.tsx
src/components/organisms/track-bar/carrots.tsx
src/components/organisms/track-bar/index.tsx
src/components/organisms/track-bar/streak.tsx
src/components/organisms/track-bar/xp-track-bar.tsx
src/components/pages/profile/history.tsx
src/components/templates/sidebar-layout/index.tsx

- Enhance UI in loading history page 
- Loading state of the table
- Fix bug cannot open side bar in mobile app
[Desktop Recording 13.webm](https://github.com/user-attachments/assets/871c5778-289b-4c13-8243-e60a57b86260)

style: table and sidebar

---

src/components/organisms/base-table.tsx

Fix this bug
Go to any table which has less than 2 pages, then click on each page, it should return the correct pages

fix: wrong page number in table navigator

---

src/components/molecules/tooltip-wrapper.tsx
src/components/organisms/gamification-stats/index.tsx
src/components/organisms/mission-section/index.tsx
src/components/organisms/streak/day-item.tsx
src/components/organisms/track-bar/index.tsx
src/components/organisms/track-bar/xp-track-bar.tsx
src/components/pages/profile/history.tsx
src/components/pages/result/result-header.tsx
src/components/templates/dashboard-layout.tsx

This PR aims to restyling some UI:
- Loading state when fetching mission
- Add shadow to tooltip
- Fix wrong UI in streak

style: mission, streak and shadow tooltip

---

index.html
public/robots.txt
public/sitemap.xml
src/App.tsx
src/i18n/i18n.tsx
src/i18n/locales/en/metadata.json
src/i18n/locales/vi/metadata.json

Add metadata title, description with multi language
Robots.txt to allow search engine crawl our data
sitemap.xml for SEO, it's recommended for new website
https://datn.atlassian.net/browse/LAP-748

feat(LAP-748): update metadata, robots and sitemap

---

src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/blank-renderer.tsx
src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/fill-in-the-blank-input.tsx
src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/index.tsx
src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/type-rendering.tsx
src/components/organisms/[module]-daily-lesson/answer-input/index.tsx

Migrate fill in the blank from mobile
https://datn.atlassian.net/browse/LAP-742

feat(LAP-742): fill in the blank

---

src/components/molecules/daily-lesson/bandscore-select.tsx
src/components/organisms/question-type-detail.tsx
src/components/organisms/question-type-list.tsx
src/routes/_authenticated/_dashboard/daily-lesson/index.tsx

No rerender list of lessons when choosing another question type

fix: question type id

---

src/components/organisms/lesson-result-dialog/index.tsx
src/components/organisms/question-type-detail.tsx
src/hooks/react-query/use-daily-lesson.ts
src/routes/_authenticated/_dashboard/daily-lesson/index.tsx
src/routes/_authenticated/daily-lesson/$dailyLessonId.tsx

After finishing lesson, the web navigates to 404 page, this PR aims to redirect it to the `daily-lesson?questionTypeId=&skill=&bandScore=`

fix: navigate after lesson

---

src/components/molecules/alert/index.tsx
src/components/organisms/select-mode-dialog/index.tsx
src/components/organisms/simulated-test-dialog/start-dialog.tsx
src/components/organisms/simulated-test-dialog/submit-dialog.tsx
src/components/pages/result/reading-listening-result.tsx
src/components/pages/simulated-test/footer.tsx
src/components/pages/simulated-test/header.tsx
src/components/pages/simulated-test/index.tsx
src/components/pages/simulated-test/timer.tsx
src/i18n/locales/en/practice.json
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/practice.json
src/i18n/locales/vi/simulated-test.json

- Highlight chữ đậm cho `SelectModeDialog`
- Thêm số câu cần hoàn thành cho SubmitDialog
- Chuyển nút submit lên header
- Chọn 1 đề --> xem chữ in đậm trên dialog select mode --> làm bài --> ấn submit --> check message
Issue link: https://datn.atlassian.net/browse/LAP-767?atlOrigin=eyJpIjoiMWIyNmU4NWI2OGVlNDhmNDg3YTRmNGRiZGM5NzE1YzIiLCJwIjoiaiJ9

fix(lap-767): change simulated test layout base on user feedback

---

src/components/pages/practice.tsx
src/components/pages/simulated-test/footer.tsx
src/components/pages/simulated-test/listening.tsx
src/hooks/react-query/use-simulated-test.ts
src/lib/utils/index.ts

Fix navigator on change part and reset order when access test again
- Change to first question in chosen part when click Next/ Prev part
- Reset to question 1 when close current test and open again.
- Navigator works correctly with parts' config
- Listening scroll to element doesn't overlay the content.
https://datn.atlassian.net/browse/LAP-766

fix(lap-766): fix navigator

---

src/assets/icons/streak-item/streak_miss.tsx
src/components/molecules/subscription-redirect-dialog.tsx
src/components/organisms/[module]-daily-lesson/answer-input/matching.tsx
src/components/organisms/global-mission-dialog.tsx
src/components/organisms/mission-section/index.tsx
src/components/organisms/mission-section/mission-list.tsx
src/components/organisms/question-type-detail.tsx
src/components/organisms/question-type-list.tsx
src/components/organisms/skill-grid.tsx
src/components/pages/[module]-daily-lesson/daily-lesson-content-page.tsx
src/components/templates/dashboard-layout.tsx
src/routes/_authenticated.tsx
src/routes/_authenticated/daily-lesson/$dailyLessonId.tsx

- Set the mission dialog global
- Check the blacklist routes to avoid rendering on daily lesson page
- Try to achieve a mission, then don't click on "Receive reward", exit the page. Then get in the dashboard again -> should show the global mission dialog
https://datn.atlassian.net/browse/LAP-787

fix(LAP-787): mission dialog appears on wrong paths

---

src/components/organisms/latest-test-section.tsx
src/hooks/react-query/use-simulated-test.ts

- Fix the latest test section (when press on the continue button, the writing and speaking test is loading infinitely)
- Do a writing/speaking --> quit --> go back via the latest test section
https://datn.atlassian.net/browse/LAP-788

fix(lap-788): fix latest test section

---

src/components/organisms/writing-submission.tsx
src/components/pages/result/writing-result.tsx
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/simulated-test.json

- Fix missing part results
- Go through all scenarios when configuring writing test (full test, practice) --> check if the results render correctly
https://datn.atlassian.net/browse/LAP-785

fix(lap-785): fix missing part results

---

src/components/molecules/daily-lesson/lesson-carousel.tsx
src/components/organisms/question-type-detail.tsx

Move the carousel to current lesson

style: current lesson index

---

src/routes/_authentication.tsx

fix(LAP-843): remove some queries fail when log out

---

src/components/ErrorFallback.tsx
src/components/molecules/floating-note/index.tsx
src/components/molecules/timer.tsx
src/components/organisms/landing-page/hero-banner.tsx
src/components/organisms/simulated-test-dialog/exit-dialog.tsx
src/components/organisms/streak/streak-section.tsx
src/components/pages/blog-details.tsx
src/components/pages/blogs.tsx
src/components/pages/landing-page.tsx
src/components/pages/simulated-test/header.tsx
src/components/pages/simulated-test/index.tsx
src/components/pages/simulated-test/speaking-header.tsx
src/components/providers/microphone-permission-provider.tsx
src/components/templates/landing-page-layout.tsx
src/components/ui/resizable.tsx
src/entry-server.tsx
src/hooks/react-query/use-public.ts
src/hooks/use-audio-recording.tsx
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/daily-lesson.json
src/i18n/locales/vi/simulated-test.json
src/services/simulated-test.ts

Fix some bugs:
- z-index of floating note < drag handler
- Enhance exit dialog typo, warning to save draft or not save
- Streak record text
- Enhance landing page header
https://datn.atlassian.net/browse/LAP-844

fix(LAP-844): exit dialog typo, streak record text, landing page header & typo

---

src/components/pages/privacy-policy.tsx
src/routeTree.gen.ts
src/routes/privacy-policy.tsx

feat: privacy policy page

---

package.json
pnpm-lock.yaml
src/components/molecules/criteria-score-card-simple.tsx
src/components/organisms/criteria-score-list.tsx
src/components/organisms/overview-evaluation-section.tsx
src/components/organisms/skill-evaluation-chart.tsx
src/components/organisms/speaking-submission/index.tsx
src/components/organisms/writing-submission/SubmissionContentAnsweredPopup.tsx
src/components/organisms/writing-submission/answered.tsx
src/components/organisms/writing-submission/color.ts
src/components/organisms/writing-submission/index.tsx
src/components/organisms/writing-submission/summary-bandscore.tsx
src/components/pages/result/writing-result.tsx
src/i18n/locales/en/simulated-test.json
src/i18n/locales/vi/simulated-test.json
src/lib/enums.ts
src/lib/types/simulated-test.type.ts
src/lib/utils/index.ts
src/routeTree.gen.ts

feat(lap-835): update new writing UI for answered section

---

package.json
server.js
src/hooks/use-audio-recording.tsx

fix: fix speaking bug

---

src/components/molecules/subscription-redirect-dialog.tsx
src/components/organisms/overview-evaluation-section.tsx
src/components/organisms/writing-submission/answered.tsx
src/components/organisms/writing-submission/index.tsx
src/components/pages/result/writing-result.tsx
src/lib/types/simulated-test.type.ts
src/lib/utils/index.ts

style: update result layout and return results base on languages changed

---

package.json
server.js
src/components/molecules/speaking-single-question-submission.tsx
src/components/molecules/subscription-redirect-dialog.tsx
src/components/organisms/overview-evaluation-section.tsx
src/components/organisms/writing-submission/answered.tsx
src/components/organisms/writing-submission/index.tsx
src/components/pages/result/speaking-result.tsx
src/components/pages/result/writing-result.tsx
src/hooks/use-audio-recording.tsx
src/i18n/locales/vi/tooltip.json
src/lib/types/simulated-test-session.type.ts
src/lib/types/simulated-test.type.ts
src/lib/utils/index.ts

FIx speaking bugs

---

src/components/organisms/evaluation-list.tsx
src/components/organisms/overview-evaluation-section.tsx
src/components/organisms/speaking-submission/index.tsx
src/components/organisms/writing-submission/answered.tsx
src/components/pages/result/speaking-result.tsx
src/lib/enums.ts

fix: update speaking result via language

---

src/components/organisms/speaking-question/speaking-part-two.tsx

fix: fix speaking part 2 question display

---

netlify.toml
src/components/molecules/subscription-redirect-dialog.tsx
src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/type-rendering.tsx
src/components/organisms/transaction-detail-sheet/index.tsx
src/hooks/react-query/useItem.ts
src/hooks/react-query/usePayment.ts
src/i18n/locales/en/profile.json
src/i18n/locales/vi/profile.json
src/services/payment.ts

- Call cancel transaction when redirect from payos
- Update carrot when get from using item
- Choose a carrot basket in shop
- Click cancel in payos
- After being redirect from payos, check transaction history and make sure the latest one's status is **cancelled**.
- buy blind box
- use, if get carrots, make sure trackbar is updated to new value

fix: call cancel when redirect

---

netlify.toml
src/components/molecules/subscription-redirect-dialog.tsx
src/components/organisms/[module]-daily-lesson/answer-input/fill-in-the-blank/type-rendering.tsx
src/components/organisms/evaluation-list.tsx
src/components/organisms/overview-evaluation-section.tsx
src/components/organisms/speaking-question/speaking-part-two.tsx
src/components/organisms/speaking-submission/index.tsx
src/components/organisms/transaction-detail-sheet/index.tsx
src/components/organisms/writing-submission/answered.tsx
src/components/pages/result/speaking-result.tsx
src/hooks/react-query/useItem.ts
src/hooks/react-query/usePayment.ts
src/i18n/locales/en/profile.json
src/i18n/locales/vi/profile.json
src/lib/enums.ts
src/services/payment.ts

feat: speaking result, cancel payment redirect

---

src/components/molecules/speaking-end-test.tsx

- Add loading spinner for Submit button

fix: add loading spinner for Submit button

---

src/i18n/locales/en/profile.json
src/i18n/locales/vi/profile.json

fix: cancel reason

---

src/components/molecules/speaking-end-test.tsx
src/i18n/locales/en/profile.json
src/i18n/locales/vi/profile.json

fix: cancel reason payment and pending speaking
